image: ros:galactic-ros-base-focal

workflow:
  # Only run on master branch and merge requests
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

variables:
  PROJECT_BASE_DIR: $CI_PROJECT_DIR

stages:
  - build

build:
  stage: build
  before_script:
    # Install ROS package dependencies
   - apt-get update -y
    # Install NotCurses
   - apt-get install -y \
            build-essential \
            cmake \
            doctest-dev \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libdeflate-dev \
            libncurses-dev \
            libqrcodegen-dev \
            libswscale-dev \
            libunistring-dev \
            pandoc \
            pkg-config \
            python3-cffi \
            python3-dev \
            python3-setuptools 
   # install pip for certain rosdep packages
    #- rosdep update -q --rosdistro=$ROS_DISTRO
    #- rosdep install -y -q --from-paths $CI_PROJECT_DIR/src --ignore-src # only choose the required packages
    #- rm -rf /var/lib/apt/lists/*
  script:
    - . /opt/ros/galactic/setup.sh
    - git submodule init
    - git submodule update
    - . $CI_PROJECT_DIR/tools/compile.sh
  variables:
    GIT_STRATEGY: clone
  artifacts:
    expire_in: 30 days
    reports:
      junit: test-results.xml
