image: registry.gitlab.com/juraph/ornis:latest

workflow:
  # Only run on master branch and merge requests
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

variables:
  PROJECT_BASE_DIR: $CI_PROJECT_DIR

stages:
  - build

build:
  stage: build
  before_script:
   - apt-get update -y

  script:
    - . /opt/ros/galactic/setup.sh
    - git submodule init
    - git submodule update
    - colcon build --event-handlers console_direct+
  variables:
    GIT_STRATEGY: clone
  artifacts:
    expire_in: 30 days
    reports:
      junit:  $CI_PROJECT_DIR/test-results.xml
