
name: ORNIS build

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  test_docker: # On Linux, iterates on all ROS 1 and ROS 2 distributions.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - foxy
          - humble
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy
            ros_version: 2
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          # Rolling Ridley (No End-Of-Life)
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install Notcurses deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            doctest-dev \
            ffmpeg \
            libavdevice-dev \
            libdeflate-dev \
            libncurses-dev \
            libqrcodegen-dev \
            libswscale-dev \
            libunistring-dev \
            pandoc \
            pkg-config \
            python3-cffi \
            python3-dev \
            python3-setuptools
      - name: Build ORNIS
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
